const firebaseConfig = {
  apiKey: "AIzaSyBFiYIeJi80X7z1cFlS05lcsswnqMWOhnA",
  authDomain: "daily-trend-battles.firebaseapp.com",
  databaseURL: "https://daily-trend-battles-default-rtdb.firebaseio.com/",
  projectId: "daily-trend-battles",
  storageBucket: "daily-trend-battles.firebasestorage.app",
  messagingSenderId: "888957436583",
  appId: "1:888957436583:web:76d91e2d05023c07ac9182"
};


// Initialize Firebase
firebase.initializeApp(firebaseConfig);
const database = firebase.database();

// ====== ONESIGNAL CONFIGURATION ======
window.OneSignalDeferred = window.OneSignalDeferred || [];
OneSignalDeferred.push(function(OneSignal) {
    OneSignal.init({
        appId: "YOUR_ONESIGNAL_APP_ID", // Add your OneSignal App ID here later
    });
});

// ====== MAIN PLATFORM ENGINE ======
document.addEventListener("DOMContentLoaded", () => {
    const container = document.getElementById("battles-container");

    // Fetch the automated static data generated by Python script
    fetch("data.json")
        .then(response => {
            if (!response.ok) throw new Error("JSON payload missing.");
            return response.json();
        })
        .then(battles => {
            if (!battles || battles.length === 0) {
                container.innerHTML = `<div class="loading">Check back later for new battles!</div>`;
                return;
            }
            container.innerHTML = ""; // Clear loading state
            
            battles.forEach(battle => {
                renderBattleCard(battle, container);
            });
        })
        .catch(err => {
            console.error(err);
            container.innerHTML = `<div class="loading">Error loading active matchups. Running updates...</div>`;
        });
});

function renderBattleCard(battle, targetContainer) {
    const card = document.createElement("div");
    card.className = "battle-card";
    
    // Check local client storage to see if user already participated
    const hasVoted = localStorage.getItem(`voted_${battle.id}`);

    card.innerHTML = `
        <span class="category-tag ${battle.category}">${battle.category}</span>
        <h2 class="battle-title">${battle.battle_title}</h2>
        <div class="vs-container" id="actions-${battle.id}">
            <button class="option-btn option-a-btn" onclick="registerVote('${battle.id}', 'option_a', '${battle.voting_api_key}')">
                <div class="progress-bar progress-a" id="bar-${battle.id}-a" style="width: 0%"></div>
                <div class="btn-content">
                    <span class="option-name">${battle.option_a}</span>
                    <span class="percentage-display" id="pct-${battle.id}-a"></span>
                </div>
            </button>
            <button class="option-btn option-b-btn" onclick="registerVote('${battle.id}', 'option_b', '${battle.voting_api_key}')">
                <div class="progress-bar progress-b" id="bar-${battle.id}-b" style="width: 0%"></div>
                <div class="btn-content">
                    <span class="option-name">${battle.option_b}</span>
                    <span class="percentage-display" id="pct-${battle.id}-b"></span>
                </div>
            </button>
        </div>
        <div class="voted-badge" id="badge-${battle.id}" style="display: ${hasVoted ? 'block' : 'none'}">
            Selection locked for today. Thanks for voting!
        </div>
    `;

    targetContainer.appendChild(card);
    
    // Wire up live listeners to Firebase for instant data rendering
    listenToLiveVotes(battle.id, battle.voting_api_key);
}

function listenToLiveVotes(battleId, votingKey) {
    const voteRef = database.ref(`battles/${votingKey}`);
    voteRef.on('value', (snapshot) => {
        const data = snapshot.val() || { option_a: 0, option_b: 0 };
        const total = data.option_a + data.option_b;
        
        let pctA = 0;
        let pctB = 0;
        
        if (total > 0) {
            pctA = Math.round((data.option_a / total) * 100);
            pctB = Math.round((data.option_b / total) * 100);
        }

        const barA = document.getElementById(`bar-${battleId}-a`);
        const barB = document.getElementById(`bar-${battleId}-b`);
        const displayA = document.getElementById(`pct-${battleId}-a`);
        const displayB = document.getElementById(`pct-${battleId}-b`);
        const hasVoted = localStorage.getItem(`voted_${battleId}`);

        if (hasVoted || total > 0) {
            if(displayA) displayA.innerText = `${pctA}%`;
            if(displayB) displayB.innerText = `${pctB}%`;
            if(barA) barA.style.width = `${pctA}%`;
            if(barB) barB.style.width = `${pctB}%`;
        }
    });
}

window.registerVote = function(battleId, selectedOption, votingKey) {
    // Anti-cheat frontend check
    if (localStorage.getItem(`voted_${battleId}`)) return;

    // Save to local device memory to lock the vote
    localStorage.setItem(`voted_${battleId}`, selectedOption);
    
    // Instantly increment vote on Firebase database endpoint
    const ref = database.ref(`battles/${votingKey}/${selectedOption}`);
    ref.transaction((currentValue) => {
        return (currentValue || 0) + 1;
    });

    // Toggle UI status
    document.getElementById(`badge-${battleId}`).style.display = "block";
};
